// Code generated by protoc-gen-go.
// source: multi/multi1.proto
// DO NOT EDIT!

/*
Package multitest is a generated protocol buffer package.

It is generated from these files:
	multi/multi1.proto
	multi/multi2.proto
	multi/multi3.proto

It has these top-level messages:
	Multi1
*/
package multitest

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Multi1 struct {
	Multi2           *Multi2         `protobuf:"bytes,1,req,name=multi2" json:"multi2,omitempty"`
	Color            *Multi2_Color   `protobuf:"varint,2,opt,name=color,enum=multitest.Multi2_Color" json:"color,omitempty"`
	HatType          *Multi3_HatType `protobuf:"varint,3,opt,name=hat_type,enum=multitest.Multi3_HatType" json:"hat_type,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Multi1) Reset()         { *m = Multi1{} }
func (m *Multi1) String() string { return proto.CompactTextString(m) }
func (*Multi1) ProtoMessage()    {}

func (m *Multi1) GetMulti2() *Multi2 {
	if m != nil {
		return m.Multi2
	}
	return nil
}

func (m *Multi1) GetColor() Multi2_Color {
	if m != nil && m.Color != nil {
		return *m.Color
	}
	return Multi2_BLUE
}

func (m *Multi1) GetHatType() Multi3_HatType {
	if m != nil && m.HatType != nil {
		return *m.HatType
	}
	return Multi3_FEDORA
}

func init() {
}
